name: 🚀 自动镜像到 Gitee

on:
  push:
    branches: [ main, master ]

jobs:
  sync_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 🥷 使用专用插件同步到 Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/RedSC1         # 你的 GitHub 用户名
          dst: gitee/RedSC1          # 你的 Gitee 用户名
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 刚才配的私钥
          dst_token: ${{ secrets.GITEE_TOKEN }}     # 之前配的 Token
          account_type: user         # 个人账户
          clone_style: "https"       # 拉取代码的方式
          force_update: true         # 强制覆盖 Gitee
          debug: true                # 开启日志方便咱们查错
          timeout: '600s'            # 防止卡死，十分钟超时
          static_list: "sxwnl_spa_dart"